# Generated by Django 3.2.7 on 2021-09-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trascript',
            new_name='Transcript',
        ),
    ]
