# Generated by Django 3.2.7 on 2021-10-02 19:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_podcast_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='s3_audio_id',
            new_name='audio_bucket_id',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='s3_transcript_id',
            new_name='audio_file_id',
        ),
        migrations.AddField(
            model_name='podcast',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast',
            name='transcript_bucket_id',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast',
            name='transcript_file_id',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), default=list, size=10),
        ),
    ]
