# Generated by Django 3.2.7 on 2021-10-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_podcast_word_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
