# Generated by Django 3.2.7 on 2021-10-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_podcast_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='word_info',
        ),
    ]
