# Generated by Django 3.2.7 on 2021-12-07 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_remove_podcast_word_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transcript',
        ),
    ]
