name: Backend Tests

on:
  push:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_2.txt
        python -m textblob.download_corpora
        python -m spacy download en_core_web_sm
        sudo apt-get install libsndfile1
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8
    - name: Coverage report
      run: |
        pip install coverage

        cd BackendConfig
        coverage run manage.py test
        coverage report
      env:
        GH_REPO: ${{ github.repository }}
        DJANGO_SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}
        RDS_PASSWORD: ${{secrets.RDS_PASSWORD}}
        RDS_HOST: ${{secrets.RDS_HOST}}
    - name: Django Testing
      run: |
        cd BackendConfig
        python3 manage.py test
      env:
        GH_REPO: ${{ github.repository }}
        DJANGO_SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}
        RDS_PASSWORD: ${{secrets.RDS_PASSWORD}}
        RDS_HOST: ${{secrets.RDS_HOST}}
    
